config/routes.rb
Rails.application.routes.draw do
  resources :users, except:[:destroy]
  devise_for :users, :controllers => {:passwords => 'passwords'}
  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
      resources :posts
      resources :comments
      resources :likes
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role.eql? 'Admin'
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def self.update_comment_counter(param)
    @post = Post.find_by_id(param[:post_id])
    @post.update(commentsCounter: param[:update_to])
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true, length: { maximum: 250 }
  validates :commentscounter, :likescounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  def self.update_post_counter(param)
    @user = User.find_by_name(param[:user])
    @user.update(postcounter: param[:update_to])
  end

  def self.last_comments(post_id)
    Post.find_by_id(post_id).comments.limit(5).order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.last_posts(user_name)
    User.find_by_name(user_name).posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name postcounter])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    Comment.update_comment_counter({ post_id: 1, update_to: 15 })
  end

  def create
    @comment = Comment.create(comment_params)
    redirect_to request.referrer if @comment.save
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referrer, notice: 'Your comment has been deleted'
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index; end

  def new
    @like = Like.new(like_params)
  end

  def create
    @like = Like.create(like_params)
    redirect_to request.referrer if @like.save
  end

  private

  def like_params
    params.require(:like).permit(:user_id, :post_id)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  # here we need to skip the automatic authentication based on current session for the following two actions
  # edit: shows the reset password form. need to skip, otherwise it will go directly to root
  # update: updates the password, need to skip otherwise it won't even reset if already logged in
  skip_before_action :require_no_authentication, only: [:edit]

  # we need to override the update, too.
  # After a password is reset, all outstanding sessions are gone.
  # When already logged in, sign_in is a no op, so the session will expire, too.
  # The solution is to logout and then re-login which will make the session right.
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = current_user
    @posts = Post.all.includes([:user])
    User.all.each { |u| u.postcounter = u.posts.count }
    @posts.each { |p| p.commentscounter = p.comments.count }

    @post = Post.new
  end

  def show
    @post = Post.find_by_id(params[:id])
    @comments = @post.comments.includes([:user])
    @comment = Comment.new
    @like = Like.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = 'Post successfully created'
    else
      flash[:alert] = 'Creation failed'
    end
    redirect_to request.referrer
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to request.referrer, notice: 'Your post has been deleted'
  end

  private

  def post_params
    params.require(:post).permit(:text, :commentscounter, :likescounter, :title, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = User.last_posts(@user.name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_comments(comments)
    comments.order('id desc').limit(5)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.erb
<%= form_with(model: comment) do |form|%>
  <%= form.text_area :text , placeholder: 'Your comment here', class: "w-100 p-2 rounded-top shadow postForm outline-border-none"%>
  <%= form.submit 'Submit', class:"button outline-border-none p-2" %>
  <%= form.hidden_field :user_id, value:current_user.id%>
  <%= form.hidden_field :post_id, value:params[:id]%>
<%end%>

app/views/layouts/_posts.html.erb
<article class="w-100 bord p-2 rounded-top my-1 shadow">
  <h5 class="p-1"><%=post.user.name%></h5>
  <h6 class="p-1"><%=post.title%></h6>
  <p class="p-1"><%= post.text %></p>
  <div class="d-flex align-items-end flex-column ">
    <div>
      <% if can? :delete, post %>
        <%= link_to 'Delete Post', "/posts/#{post.id}", method: :delete, class:"btn button p-1" %>
      <% end %>
    </div>
    <section class="d-flex">
      <div class="p-1"> Comments: <%=post.comments.count%></div>
      <div class="p-1"> Likes: <%=post.likes.count%></div>
    </section>
  </div>
</article>

app/views/layouts/_profile.html.erb
<section class="profileWrapper w-100">
  <section class="d-flex justify-content-between profileContainer">
      <article>
        <%= image_tag "profile.png" %>
      </article>
      <article class="w-75 d-flex justify-content-around bord p-2 rounded-top shadow">
        <div class="align-self-center"><h1><%= @user.name %></h1></div>
        <div class="align-self-center"><h5>Number of posts:<%= @user.postcounter %></h5></div>
      </article>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeaningfulName</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="container-md mx-auto">
    <% if notice %>
      <p class="alert deepPurple p-1 outline-border-none"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert pink deepPurple p-1 outline-border-none"><%= alert %></p>
    <% end %>
    <%if current_user%>
      <header>
        <div><%= link_to 'Signout', destroy_user_session_path, method: :delete %></div>
        <div><%= link_to 'Change password', edit_user_registration_url%></div>
      </header>
    <% end %>
    <%= yield%>
  </body>
</html>

app/views/likes/index.html.erb
<h1>Likes </h1>
<%= current_user.name %>

app/views/posts/_like_form.html.erb
<%= form_with(model:like, html:{class:"txt-right"}) do |form|%>
  <%= form.submit 'Like', class:"button outline-border-none p-2 likeBtn shadow"%>
  <%= form.hidden_field :user_id, value:current_user.id%>
  <%= form.hidden_field :post_id, value:params[:id]%>
<%end%>

app/views/posts/_post_form.html.erb
<%= form_with(model: post , html:{class: "w-100 p-2 rounded-top mb-5 shadow"}) do |form| %>
  <%= form.text_area :text , placeholder: 'Your post here', class: "w-100 p-2 rounded-top shadow postForm outline-border-none"%>
  <%= form.hidden_field :commentscounter, value: 0 %>
   <%= form.hidden_field :likescounter, value: 0 %>
  <%= form.submit 'Submit', class:"button outline-border-none p-2" %>

<%end%>

app/views/posts/index.html.erb
<%= render 'layouts/profile'%>
<%= render 'post_form', :post => @post %>
<% @posts.each do |p| %>
  <%= link_to "/posts/#{p.id}" do %>
    <article class="w-100 p-2 rounded-top mb-5 shadow">
      <%= render 'layouts/posts', :post =>p %>
    <%end %>
    <% if p.comments.count > 0 %>
      <p class="p-1">Comments:</p>
      <article class="w-100 bord p-2 rounded-top shadow">
        <%render_comments(p.comments.includes([:user])).each do |c| %>
          <p><%=c.user.name %>: <%= c.text%></p>
        <%end%>
      <%end%>
    </article>
  </article>
<%end%>

app/views/posts/show.html.erb
<article class="w-100 bord p-2 rounded-top mb-4 my-5 shadow">
  <section class="d-flex justify-content-between postsBy">
    <div>
      <h5>Post # <%=@post.id %> by <%= @post.user.name %></h5>
    </div>
    <div class="align-self-end">
      <p>Comments: <%=@post.comments.count%> Likes: <%=@post.likes.count%></p>
    </div>
  </section>
  <section class="postsText mt-2">
    <p><%= @post.text%></p>
  </section>
  <section class="mb-3 text-right">
    <%= render 'posts/like_form', :like => @like, :post => @post.id %>
  </section>
  <section class="p-2 shadow">
    <%= render 'comments/comment_form', :comment => @comment%>
    <% @comments.each do |comment| %>
      <div class="d-flex justify-content-between align-items-center">
        <p><%= comment.user.name %> : <%= comment.text %></p>
        <%if can? :delete, comment %>
          <div>
            <%= link_to 'Delete Comment', "/comments/#{comment.id}",method: :delete,class:"btn button p-1"%>
          </div>
        <% end %>
      </div>
    <% end %>
  </section>
</article>

app/views/users/index.html.erb
<div class=" w-100 py-5"> 
  <%@user.each do |user| %>
  <section class="d-flex justify-content-between profileContainer">
    <article>
      <%= image_tag "profile.png" %>
    </article>
    <%= link_to user,user_id:user.id, class:"w-75 d-flex justify-content-around bord p-2 rounded-top shadow" do %>
      <div class="align-self-center"><h1><%= user.name %></h1></div>
      <div class="align-self-end"><p>Number of posts <%= user.postcounter %></p></div>
    <%end%>
  </section>
    <%end%>
</div>

app/views/users/show.html.erb
<%= render 'layouts/profile', :user => @user%>
<article class="w-100 bord p-2 rounded-top shadow">
  <h5 class="p-1">Bio</h5>
  <p class="p-1"><%= @user.bio %></p>
  <p> Number of posts:<%= @user.postcounter %></P>
</article>

<% @posts.each do |post| %>
  <%= render 'layouts/posts', :post =>post %>
<% end %>
<div class="d-flex justify-content-center">
<%= link_to 'Show all posts',posts_path, class:"btn button p-3 m-3" %>
</div> 